version: '2'
services:
  web:
    build:
      context: .
      #args:
      #  VERSION: "${VERSION}"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    links:
     - postgres
    depends_on:
     - postgres
    entrypoint: ./scripts/wait-for-postgres.sh postgres ./scripts/start-server.sh
  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
